controllers:
    resource: ../src/Controller/
    type: attribute

app_logout:
    path: /logout
    #controller: App\Controller\LoginController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::index
homepage:
    path: /test
    controller: App\Controller\DialogController::defaultAction

admin_new_article:
    path: /admin/new-article
    controller: App\Controller\AdminController::newArticle

troll_api_endpoint:
    path: /api/troll
    controller: App\Controller\DialogController::apiAction

api_custom_upload_file:
    path: /apic/new-image
    controller: App\Controller\ImageUploadApiController::index
    methods: POST

steam_api_cart_content:
    path: /apic/steam/cart
    controller: App\Controller\SteamApiController::cartGetContent
    methods: GET


steam_api_remove_game_from_cart:
    path: /apic/steam/cart/{gameid}
    controller: App\Controller\SteamApiController::deleteFromCart
    methods: DELETE
    requirements:
        gameid: \d+

steam_api_add_game_into_cart:
    path: /apic/steam/cart
    controller: App\Controller\SteamApiController::addToCart
    methods: POST




page_index_steam:
    path: /
    controller: App\Controller\SteamController::index

page_produit_steam:
    path: /product/{slug}
    controller: App\Controller\SteamController::product
    requirements:
        slug: '[a-zA-Z0-9\-_\/]+'

page_form_steam:
    path: /form
    controller: App\Controller\SteamController::form

page_cart_content:
    path: /cart
    controller: App\Controller\SteamController::cartContent

search_game_steam:
    path: /search
    controller: App\Controller\SteamController::search